# Set the language
language: node_js

# Set the Node version
node_js:
  - '14.17.4'

services:
  # Use Docker command line
  # - docker

install:
  # Install dependencies for tests
  # - npm ci

addons:
  sonarcloud:
    organization: 'devops-dislinkt-team'
    token:
      secure: 843425204abdaf8a3d40ff2c5ec0bcb453e6a29e

before_script:
  # Start server and client for tests
  # - npm run dev &

script:
  # Run tests
  # - npm run test
  - sonar-scanner -X

branches:
  only:
    - main
    - develop
